language: php
php:
    - 7.3
    - 7.2
    - 7.1
    - 7.0

env:
    - LIBZOOKEEPER_VERSION=3.5.3-beta
    - LIBZOOKEEPER_VERSION=3.4.12

addons:
  apt:
    packages:
      - lcov

sudo: false

install:
    - gem install coveralls-lcov

before_script:
    - ./.travis/install_libzookeeper.sh $LIBZOOKEEPER_VERSION

script:
    - ./.travis/build.sh $LIBZOOKEEPER_VERSION

after_success:
    - coveralls-lcov coverage.info

