language: php
php:
    - 8.2
    - 8.1
    - 8.0
    - 7.3
    - 7.2
    - 7.1
    - 7.0

env:
    - LIBZOOKEEPER_VERSION=3.7.1
    - LIBZOOKEEPER_VERSION=3.6.4
    - LIBZOOKEEPER_VERSION=3.5.9
    - LIBZOOKEEPER_VERSION=3.4.14

jobs:
    include:
        - dist: bionic
          php: 8.1.0
        - dist: bionic
          php: 8.2.0

addons:
  apt:
    packages:
      - lcov
      - ant
      - libcppunit-dev

sudo: false

install:
    - gem install coveralls-lcov

before_script:
    - ./.travis/install_libzookeeper.sh $LIBZOOKEEPER_VERSION

script:
    - ./.travis/build.sh $LIBZOOKEEPER_VERSION

after_success:
    - coveralls-lcov coverage.info
